##########################################################################################################################
# A brief script for analysing breakends with the GRIDSS software package. 
##########################################################################################################################
data=/kakapo-data/bwa/
ref=/kakapo-data/References/kakapo_full_ref.fa
exclude=/kakapo-data/metadata/kakapo_SVexcluded_scaffolds.bed
jar=~/anaconda3/envs/gridss/share/gridss-2.12.2-0/gridss.jar

gridss \
  -r ${ref} \
  -j gridss-2.X.Y-gridss-jar-with-dependencies.jar \
  -o ${data}gridss/kakapo_gridss_output.vcf \
  -w ${data}gridss/temp \
  -b ${exclude} \
  -j ${jar} \
  --skipsoftcliprealignment \
  --threads 24 \
  --maxcoverage 10000 \
  /kakapo-data/bwa/bwa_female/markdup/batch01/Adelaide_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch01/Alice_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch01/Aparima_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch01/Aranga_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch01/Atareta_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch01/Aumaria_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch01/Awarua_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch02/Bella_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch02/Boomer_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch02/Cyndy_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch02/Dusky_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch02/Ellie_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch02/Esperance_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch02/Evohe_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch03/Flossie_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch03/Fuchsia_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch03/Gertrude_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch03/Hakatere_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch03/Hananui_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch03/Hauturu_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch03/Heather_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch04/Hera_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch04/Hinemoa_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch04/Hine_Taumai_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch04/Hoki_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch04/Huhana_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch04/Ihi_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch04/Jean_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch05/Jemma_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch05/JEM_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch05/Konini_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch05/Kuia_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch05/Kuihi_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch05/Kura_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch05/Lisa_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch06/Maggie_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch06/Mahli_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch06/Makorea_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch06/Marama_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch06/Margaret-Maree_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch06/Marian_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch06/Mila_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch07/Millie_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch07/Mukeke_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch07/Ninihi_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch07/Nora_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch07/Pearl_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch07/Pounamu_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch07/Pura_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch08/Queenie_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch08/Rakiura_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch08/Ra_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch08/Rimu_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch08/Roha_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch08/Ruth_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch08/Sandra_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch09/Sarah_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch09/Solstice_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch09/Stella_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch09/Sue_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch09/Suzanne_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch09/Tiaka_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch09/Tia_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch10/Titapu_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch10/Tiwhiri_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch10/Tohu_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch10/Toitiiti_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch10/Tukaha_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch10/Tumeke_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch10/Waa_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch11/Waikawa_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch11/Weheruatanga-o-te-po_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch11/Wendy_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch11/Yasmine_markdup.bam \
  /kakapo-data/bwa/bwa_female/markdup/batch11/Zephyr_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch01/Al_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch01/Arab_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch01/Attenborough_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch01/Awhero_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch01/Barnard_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch01/Basil_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch02/Ben_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch02/Bill_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch02/Blades_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch02/Blake_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch02/Bluster_Murphy_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch02/Bonus_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch02/Boss_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch03/Clout_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch03/Dobbie_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch03/Doc_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch03/Egilsay_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch03/Elliot_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch03/Elwin_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch03/Faulkner_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch04/Felix_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch04/George_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch04/Guapo_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch04/Gulliver_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch04/Gumboots_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch04/Gunner_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch04/Henry_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch05/Hillary_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch05/Hokonui_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch05/Horton_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch05/Hugh_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch05/Hurihuri_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch05/Ian_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch05/Jack_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch06/Jamieson_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch06/Jester_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch06/Joe_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch06/Juanma_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch06/Kanawera_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch06/Kokoto_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch07/Komaru_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch07/Konini_3-4-16_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch07/Kotiu_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch07/Kumi_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch07/Lee_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch07/Lionel_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch07/Luke_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch08/Manu_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch08/Matangi_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch08/Merty_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch08/Merv_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch08/Moorhouse_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch08/Morehu_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch08/Moss_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch09/Ngatapa_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch09/Nog_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch09/Oraka_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch09/Ox_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch09/Paddy_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch09/Palmersan_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch09/Percy_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch10/Piripi_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch10/Ralph_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch10/Rangi_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch10/Richard_Henry_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch10/Robbie_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch10/Ruapuke_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch10/Ruggedy_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch11/Sass_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch11/Scratch_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch11/Sinbad_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch11/Sirocco_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch11/Smoko_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch11/Stumpy_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch11/Taeatanga_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch12/Takitimu_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch12/Tamahou_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch12/Tau_Kuhurangi_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch12/Te_Atapo_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch12/Te_Awa_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch12/Te_Here_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch12/Te_Kingi_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch13/Tiwai_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch13/Trevor_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch13/Tuterangi_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch13/Tutoko_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch13/Waihopai_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch13/Wharetutu_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch14/Whiskas_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch14/Wiremu_markdup.bam \
  /kakapo-data/bwa/bwa_male/markdup/batch14/Wolf_markdup.bam